### ISSUE TITLE
Cannot start the pane closed

### ISSUE THREAD

**Issue by marcofugaro** [tweakpane/use-tweaks#39]
Passing `{ expanded: false }` as a third argument (the option argument) does not work.

<img src="https://user-images.githubusercontent.com/7217420/100993955-55549c00-3556-11eb-81ef-81ef55112bfb.png" width="400" />

Reproducible here:
https://codesandbox.io/s/use-tweaks-example-forked-j22p4?file=/src/App.js

## Current Result
<img src="https://user-images.githubusercontent.com/7217420/100993840-2fc79280-3556-11eb-8ecd-9d2ea3478a2a.png" width="350" />

## Expected Result

<img src="https://user-images.githubusercontent.com/7217420/100993873-36eea080-3556-11eb-8126-98bad86e4970.png" width="350" />

It should forward correctly the options to tweakpane:
https://cocopon.github.io/tweakpane/api/classes/rootapi.html#expanded

**Comment by cocopon** [comment]
Fixed in 0.3.2-alpha.0.
