### ISSUE TITLE
`tweakpane` version ^3.0 introduces breaking changes

### ISSUE THREAD

**Issue by nhtranngoc** [tweakpane/use-tweaks#45]
`tweakpane` recently upgraded to version 3, which introduced breaking changes:

https://github.com/cocopon/tweakpane/releases/tag/3.0.0

Running `use-tweaks`  gives the following error:
![image](https://user-images.githubusercontent.com/5572645/124508872-b79ca600-dd9e-11eb-941c-fba4e3992d5f.png)

Changes including named exports, types changes, and refactored routes in `types/api/`. I will try and push a PR if I got the time.

**Comment by nhtranngoc** [comment]
Alternatively, downgrading `tweakpane` to versions `2.4.3` and under works.

**Comment by gsimone** [comment]
Hey, we are not really maintaining this, since we moved on to Leva https://github.com/pmndrs/leva

let me know if you are interested in maintaining/developing this!

**Comment by cocopon** [comment]
Just released 0.3.2-alpha.0 and now supports the latest version of Tweakpane (v3).
